<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKDGScQ9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKDGScQ9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKDGScQ9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKDGScQ9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKDGScQ9\App_KernelDevDebugContainer([
    'container.build_hash' => 'KDGScQ9',
    'container.build_id' => '088a4ddf',
    'container.build_time' => 1661007307,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKDGScQ9');
