<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxwjuOr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxwjuOr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxwjuOr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxwjuOr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxwjuOr\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxwjuOr',
    'container.build_id' => '844f49ab',
    'container.build_time' => 1661018858,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxwjuOr');
